resources:
  - ../../../base
namePrefix: gpu-
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: neuronpedia-inference
      spec:
        template:
          spec:
            containers:
            - name: neuronpedia-inference
              image: gcr.io/$(PROJECT_ID)/neuronpedia-inference:gpu
              imagePullPolicy: Always
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: "10"
                  memory: "70Gi"
                limits:
                  nvidia.com/gpu: 1
                  cpu: "12"
                  memory: "80Gi"
