services:
    graph:
      volumes:
        - ./apps/graph:/app/apps/graph
      environment:
        - RELOAD=${RELOAD:-0}
      command: >
        sh -c "cd /app/apps/graph && python neuronpedia_graph/server.py google/gemma-2-2b" 